kind: pipeline
type: docker
name: test

steps:
  - name: Test Python
    image: python:3.12
    commands:
      - curl -L "https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-$(dpkg --print-architecture)" > "${HOME}/bin/cc-test-reporter"
      - chmod +x "${HOME}/bin/cc-test-reporter"
      - pip install -e .[test]
      - ruff check .
      - mypy .
      - cc-test-reporter before-build
      - coverage run -m unittest
      - exitcode="$?"
      - coverage report -m
      - coverage xml
      - cc-test-reporter after-build --exit-code "$exitcode"
    environment:
      CC_TEST_REPORTER_ID: 2baac9a046cac4e8790932772e1c9954ed0d6786e55a011f32dcc30da97781a1

  - name: Test Python Packaging
    image: python:3.12
    commands:
      - pip install build twine
      - python -m build
      - twine check --strict dist/*

  - name: Upload Python
    depends_on:
      - Test Python
      - Test Python Packaging
    environment:
      TWINE_USERNAME:
        from_secret: twine_username
      TWINE_PASSWORD:
        from_secret: twine_password
    image: python:3.12
    commands:
      - pip install build twine
      - python -m build
      - twine upload dist/*
    when:
      event:
        - tag
